version: "3"
services:
  app:
    build:
      context: .

    depends_on:
      - postgres

    container_name: python-app
    volumes:
      - ~/workspace:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro
    environment:
      - DB_HOST=postgres
      - DB_NAME=app
      - DB_USER=app

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_HOST_AUTH_METHOD=trust
